//
//  Answer.swift
//  NoesisNoema
//
//  Created by Раскольников on 2025/07/25.
//

class Answer: CustomStringConvertible
{
    /**
     * Represents an answer generated by a language model.
     *
     - Properties:
     *   - text: The text of the answer.
     *   - score: The score of the answer, indicating its relevance or confidence level.
     *   - metadata: Additional metadata associated with the answer, such as source or context.
     */
    var text: String
    var score: Float
    var metadata: [String: Any]?
    
    /**
     * Initializes an Answer with the specified properties.
     * - Parameter text: The text of the answer.
     * - Parameter score: The score of the answer.
     * - Parameter metadata: Optional metadata associated with the answer.
     */
    init(text: String, score: Float, metadata: [String: Any]? = nil) {
        self.text = text
        self.score = score
        self.metadata = metadata
    }
    /**
        * A string representation of the Answer object.
        * This is used for debugging and logging purposes.
        * - Returns: A string containing the text and score of the answer.
        */
    var description: String {
        return "Answer(text: \(text), score: \(score), metadata: \(String(describing: metadata)))"
    }
    
}
