name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-sanity:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Git LFS & fetch LFS objects
        run: |
          set -euxo pipefail
          brew install git-lfs || true
          git lfs install
          git lfs pull

      - name: Xcode version
        run: |
          xcodebuild -version
          sw_vers

      - name: Build LlamaBridgeTest (Debug, no code signing)
        run: |
          set -euxo pipefail
          xcodebuild -scheme LlamaBridgeTest \
            -project "NoesisNoema.xcodeproj" \
            -configuration Debug \
            -destination 'platform=macOS' \
            -derivedDataPath ci_build \
            CODE_SIGNING_ALLOWED=NO \
            MACOSX_DEPLOYMENT_TARGET=15.0 \
            ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO \
            build | cat

      - name: "Sanity: nn model info --dry-run"
        run: |
          set -euxo pipefail
          ./ci_build/Build/Products/Debug/LlamaBridgeTest model info jan-v1-4b --dry-run

      - name: Run CLI tests
        run: |
          set -euxo pipefail
          ./ci_build/Build/Products/Debug/LlamaBridgeTest model test
